class GraphqlController < ApplicationController
  def execute: () -> untyped

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables: (untyped variables_param) -> untyped

  def handle_error_in_development: (untyped e) -> untyped
end
