require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/tasks/rbs.rake'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Style/StringLiterals:
  Exclude:
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Exclude:
    - 'bin/bundle'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false