# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.3'

gem 'bootsnap', require: false
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'silencer', '2.0.0'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '6.2.0'
  gem 'rspec-rails', '5.1.2'
end

group :development do
  gem 'rubocop-performance', '1.13.3', require: false
  gem 'rubocop-rails', '2.14.2', require: false
  gem 'rubocop-rspec', '2.11.1', require: false
end
