# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '~> 7.0.3'

gem 'active_storage_validations'
gem 'aws-sdk-s3', require: false
gem 'bcrypt'
gem 'bootsnap', require: false
gem 'graphql'
gem 'graphql-rails_logger'
gem 'image_processing'
gem 'jwt'
gem 'pg'
gem 'puma'
gem 'rack-cors'
gem 'rails-i18n'
gem 'ruby-vips'
gem 'silencer'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'bullet'
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'graphql-schema_comparator'
  gem 'rspec-rails'
  gem 'steep'
end

group :development do
  gem 'annotate'
  gem 'rbs_rails', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'seed-fu'
end

group :test do
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
end
